# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 20
    ignore:
      - dependency-name: org.ajoberstar.grgit
        update-types: ["version-update:semver-major"]
      - dependency-name: HikariCP
        update-types: ["version-update:semver-major"]
      - dependency-name: caffeine
        update-types: ["version-update:semver-major"]

