image: java:8

# Disable the Gradle daemon for Continuous Integration servers as correctness
# is usually a priority over speed in CI environments. Using a fresh
# runtime for each build is more reliable since the runtime is completely
# isolated from any previous builds.
variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

stages:
  - build
  - pitest
  - deploy

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle
  - chmod +x gradlew

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

build:
  stage: build
  script: ./gradlew build
  coverage: '/simple-pki: \d+.\d+/'
  artifacts:
    paths:
      - public

pitest:
  stage: pitest
  script: ./gradlew pitest
  artifacts:
    paths:
      - public

docker push:
  stage: deploy
  script: >
    ./gradlew jib -PdockerRegistry=${CI_REGISTRY} -PdockerGroup=${CI_PROJECT_NAMESPACE}
    -Djib.to.auth.username=${CI_REGISTRY_USER}
    -Djib.to.auth.password=${CI_REGISTRY_PASSWORD}
    -Djib.console=plain

pages:
  stage: deploy
  script: "true"
  artifacts:
    paths:
      - public

