version: '3.3'

services:
  db:
    image: mariadb:latest
    container_name: mariadb
    ports:
    - "3306:3306"
    volumes:
    - ./data/mariadb:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: OtJagbee
      MYSQL_DATABASE: pki
      MYSQL_USER: user
      MYSQL_PASSWORD: seacKoop
