management:
  endpoints:
    web:
      exposure:
        include: ["health", "info"]
logging:
  pattern:
    console: "%clr(%d{yyyy-MM-dd'T'HH:mm:ss.SSSZ}){faint} %clr(%5p) %m%n%wEx"
spring:
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  datasource:
    url: jdbc:h2:file:/data/pki
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: true
app:
    pki:
        ks:
            resource: file:/data/ca.p12
            alias: ca
            type: pkcs12
            storepass: changeit
            keypass: changeit
