management:
  endpoints:
    web:
      exposure:
        include: [ "health", "info" ]
logging:
  pattern:
    console: "%clr(%d{yyyy-MM-dd'T'HH:mm:ss.SSSZ}){faint} %clr(%5p) %m%n%wEx"
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: pki
    hikari:
      maximum-pool-size: 10
  flyway:
    connect-retries: 10
    connect-retries-interval: 2s
    default-schema: &default-schema pki
  jpa:
    properties:
      hibernate:
        default_schema: *default-schema
app:
  pki:
    ks:
      resource: classpath:/data/ca.p12
      alias: ca
      type: pkcs12
      storepass: changeit
      keypass: changeit
server:
  error:
    include-message: always
