[versions]
archunit = "1.0.0"
awaitility = "4.2.0"
bouncycastle = "1.72"
commons-text = "1.10.0"
kotlin_lang = "1.7.20"
kotlin-logging = "3.0.3"
logcaptor = "2.7.10"
mapstruct = "1.5.3.Final"
restdocs-apispec = "0.16.2"
semver4j = "0.16.4"
spock_bom = "2.3-groovy-3.0"
spock-reports = "2.3.1-groovy-3.0"
testcontainers = "1.17.5"
