apiVersion: v1
kind: Service
metadata:
  name: simple-pki
  labels:
    app: simple-pki
spec:
  ports:
  - port: 8080
    name: pki
  selector:
    app: simple-pki
  type: ClusterIP

---

apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: pki
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-pki
  template:
    metadata:
      labels:
        app: simple-pki
    spec:
      containers:
      - name: simple-pki
        image: registry.gitlab.com/ebo/simple-pki:1.1.0
        imagePullPolicy: Always
        envFrom:
          - prefix: APP_PKI_
            secretRef:
              name: ca-jks-keys
          - prefix: SPRING_DATASOURCE_
            secretRef:
              name: db-embedded-h2
        env:
          - name: APP_PKI_KS_RESOURCE
            value: 'file:/data/jks/ca.p12'
        ports:
        - containerPort: 8080
          name: pki
        readinessProbe:
          httpGet:
            port: pki
            path: /healthz
          initialDelaySeconds: 15
          periodSeconds: 5
        livenessProbe:
          httpGet:
            port: pki
            path: /healthz
          initialDelaySeconds: 10
          periodSeconds: 10
        volumeMounts:
        - name: db
          mountPath: /data/db
        - name: jks
          mountPath: /data/jks
      volumes:
        - name: db
          persistentVolumeClaim:
            claimName: db
        - name: jks
          configMap:
            name: ca-jks-data
      imagePullSecrets:
        - name: gl-regcred

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db
spec:
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: 10Mi
