---
name: Check

on:
  pull_request:
    branches:
      - '!release-please-*'

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'gradle'

      - name: clean check
        run: ./gradlew clean build --no-daemon --info --stacktrace
...
